### ISSUE TITLE
Leaderboards loading

### ISSUE THREAD

**Issue by azuspl** [Flatracer/DemolitionDerbyGamemode#19]
Hey, small problem with leaderboards, yeah it saving stats in map.json files and it looks like this:

```
{
    "9056959a360df9538d14664beb98248661f29368":{"Lost":0,"Name":"Azus","Won":2}
} 
```
But it not loading these stats and not updating them on map

**Comment by Flatracer** [comment]
It does work for me, just tested it.

Can you be a bit more specific?

**Comment by Flatracer** [comment]
No response, so I guess there is no issue...

Reopen if there is.
