### ISSUE TITLE
Scoreboard not updating

### ISSUE THREAD

**Issue by smishcraft** [Flatracer/DemolitionDerbyGamemode#20]
Hi,

The scoreboard is not updating although the json files are.

Any ideas?

Server is running on linux, I have not tested with windows.

Kind Regards
Smish

**Comment by Flatracer** [comment]
Do you mean the small rectangle on the right side of the screen?
If so, we are aware of that. It is currently broken.

But if you mean the Leaderboard, which opens with F9, tell me.

**Comment by Flatracer** [comment]
No response from the OP. Closing now.

**Comment by ScottUK** [comment]
Issue was with the UI located in UI.lua - The win / loss section of this leaderboard has now been removed.
